"""
Django settings for need_to_do project.

Generated by 'django-admin startproject' using Django 3.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-3zwd_-@qck6g1%na&4c$uewlgrne7px8%s7$*jv2u7#t#@!=rz')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')

# 上传文件大小和字段数量限制（支持大量题目导入）
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quiz',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'quiz.middleware.AntiSpiderMiddleware',
]

LOGIN_URL = '/quiz/login/'

ROOT_URLCONF = 'need_to_do.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'need_to_do.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'need_to_do'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'Netsky121666880!'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            'use_unicode': True,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('zh-hans', '简体中文'),
    ('en', 'English'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SimpleUI 配置 - 现代化后台管理界面
SIMPLEUI_HOME_TITLE = '📚 在线考试系统管理后台'
SIMPLEUI_HOME_ICON = 'fa-solid fa-graduation-cap'
# 移除不存在的logo配置，使用默认logo
# SIMPLEUI_LOGIN_LOGO = '/static/admin/simpleui-x/logo.png'
# SIMPLEUI_LOGO = '/static/admin/simpleui-x/logo.png'

SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_style': 'sidebar',  # 侧边栏菜单样式
    'menus': [
        {
            'name': '👥 用户管理',
            'icon': 'fa-solid fa-users',
            'models': [
                {
                    'name': '👤 用户列表',
                    'icon': 'fa-solid fa-user-pen',
                    'url': 'auth/user/'
                },
                {
                    'name': '👥 用户组',
                    'icon': 'fa-solid fa-user-group',
                    'url': 'auth/group/'
                },
                {
                    'name': '🎫 会员信息',
                    'icon': 'fa-solid fa-id-card',
                    'url': 'quiz/profile/'
                }
            ]
        },
        {
            'name': '📝 题库管理',
            'icon': 'fa-solid fa-book-open',
            'models': [
                {
                    'name': '📄 题目管理',
                    'icon': 'fa-solid fa-file-lines',
                    'url': 'quiz/question/'
                },
                {
                    'name': '📥 导入试题',
                    'icon': 'fa-solid fa-file-import',
                    'url': '/quiz/admin/import_questions/'
                },
                {
                    'name': '📋 下载导入模板',
                    'icon': 'fa-solid fa-file-arrow-down',
                    'url': '/quiz/admin/import_questions/template/'
                }
            ]
        },
        {
            'name': '📋 试卷管理',
            'icon': 'fa-solid fa-file-text',
            'models': [
                {
                    'name': '📜 试卷列表',
                    'icon': 'fa-solid fa-scroll',
                    'url': 'quiz/testpaper/'
                },
                {
                    'name': '📝 后台组卷',
                    'icon': 'fa-solid fa-pen-to-square',
                    'url': '/quiz/admin/create_testpaper/'
                },
                {
                    'name': '📥 导入试卷',
                    'icon': 'fa-solid fa-file-import',
                    'url': '/quiz/admin/import_testpaper/'
                },
                {
                    'name': '📄 下载导入模板',
                    'icon': 'fa-solid fa-file-arrow-down',
                    'url': '/quiz/admin/import_questions/template/'
                }
            ]
        },
        {
            'name': '📊 答题记录',
            'icon': 'fa-solid fa-chart-line',
            'models': [
                {
                    'name': '📈 答题记录',
                    'icon': 'fa-solid fa-chart-bar',
                    'url': 'quiz/testrecord/'
                },
                {
                    'name': '✅ 每题答题记录',
                    'icon': 'fa-solid fa-list-check',
                    'url': 'quiz/answerrecord/'
                },
                {
                    'name': '❌ 错题本',
                    'icon': 'fa-solid fa-circle-exclamation',
                    'url': 'quiz/wrongquestion/'
                }
            ]
        },
        {
            'name': '🏫 班级管理',
            'icon': 'fa-solid fa-school',
            'models': [
                {
                    'name': '🏠 班级列表',
                    'icon': 'fa-solid fa-building',
                    'url': 'quiz/class/'
                },
                {
                    'name': '📝 班级申请',
                    'icon': 'fa-solid fa-file-signature',
                    'url': 'quiz/classapplication/'
                }
            ]
        }
    ]
}

# ==============================================================================
# 性能优化配置
# ==============================================================================

# 缓存配置 - 使用本地内存缓存提高性能
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 缓存超时时间（秒）
        'OPTIONS': {
            'MAX_ENTRIES': 10000,  # 最大缓存条目数
            'CULL_FREQUENCY': 3,  # 缓存满时删除1/3的旧条目
        }
    }
}

# 会话配置优化
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 使用数据库存储会话
SESSION_COOKIE_AGE = 86400  # 会话超时时间（秒）= 24小时
SESSION_SAVE_EVERY_REQUEST = False  # 不是每次请求都保存会话
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 浏览器关闭时不删除会话

# 自动重新加载配置（开发环境）
if DEBUG:
    # 开发模式下使用更快的文件监视
    WATCHFILES_CHANGED_DELAY = 1000  # 毫秒

# 数据库连接池配置
DATABASES['default'].update({
    'CONN_MAX_AGE': 60,  # 数据库连接复用时间（秒）
    'OPTIONS': {
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        'charset': 'utf8mb4',
        'use_unicode': True,
    }
})

# 静态文件缓存（使用 WhiteNoise 压缩和缓存支持）
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 模板缓存（开发环境已禁用）
# TEMPLATES[0]['OPTIONS']['loaders'] = [
#     ('django.template.loaders.cached.Loader', [
#         'django.template.loaders.filesystem.Loader',
#         'django.template.loaders.app_directories.Loader',
#     ]),
# ]

# 中间件优化 - 启用条件GET中间件
MIDDLEWARE += [
    'django.middleware.http.ConditionalGetMiddleware',
]
