"""
Django settings for need_to_do project.

Generated by 'django-admin startproject' using Django 3.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3zwd_-@qck6g1%na&4c$uewlgrne7px8%s7$*jv2u7#t#@!=rz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quiz',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = '/quiz/login/'

ROOT_URLCONF = 'need_to_do.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'need_to_do.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'need_to_do',
        'USER': 'root',
        'PASSWORD': 'Netsky121666880!',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ('zh-hans', '简体中文'),
    ('en', 'English'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SimpleUI 配置 - 现代化后台管理界面
SIMPLEUI_HOME_TITLE = '📚 在线考试系统管理后台'
SIMPLEUI_HOME_ICON = 'fa-solid fa-graduation-cap'
SIMPLEUI_LOGIN_LOGO = '/static/admin/simpleui-x/logo.png'
SIMPLEUI_LOGO = '/static/admin/simpleui-x/logo.png'

SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menu_style': 'sidebar',  # 侧边栏菜单样式
    'menus': [
        {
            'name': '👥 用户管理',
            'icon': 'fa-solid fa-users',
            'models': [
                {
                    'name': '👤 用户列表',
                    'icon': 'fa-solid fa-user-pen',
                    'url': 'auth/user/'
                },
                {
                    'name': '👥 用户组',
                    'icon': 'fa-solid fa-user-group',
                    'url': 'auth/group/'
                },
                {
                    'name': '🎫 会员信息',
                    'icon': 'fa-solid fa-id-card',
                    'url': 'quiz/profile/'
                }
            ]
        },
        {
            'name': '📝 题库管理',
            'icon': 'fa-solid fa-book-open',
            'models': [
                {
                    'name': '📄 题目管理',
                    'icon': 'fa-solid fa-file-lines',
                    'url': 'quiz/question/'
                }
            ]
        },
        {
            'name': '📋 试卷管理',
            'icon': 'fa-solid fa-file-text',
            'models': [
                {
                    'name': '📜 试卷列表',
                    'icon': 'fa-solid fa-scroll',
                    'url': 'quiz/testpaper/'
                }
            ]
        },
        {
            'name': '📊 答题记录',
            'icon': 'fa-solid fa-chart-line',
            'models': [
                {
                    'name': '📈 答题记录',
                    'icon': 'fa-solid fa-chart-bar',
                    'url': 'quiz/testrecord/'
                },
                {
                    'name': '✅ 每题答题记录',
                    'icon': 'fa-solid fa-list-check',
                    'url': 'quiz/answerrecord/'
                },
                {
                    'name': '❌ 错题本',
                    'icon': 'fa-solid fa-circle-exclamation',
                    'url': 'quiz/wrongquestion/'
                }
            ]
        },
        {
            'name': '🏫 班级管理',
            'icon': 'fa-solid fa-school',
            'models': [
                {
                    'name': '🏠 班级列表',
                    'icon': 'fa-solid fa-building',
                    'url': 'quiz/class/'
                },
                {
                    'name': '📝 班级申请',
                    'icon': 'fa-solid fa-file-signature',
                    'url': 'quiz/classapplication/'
                }
            ]
        }
    ]
}
