# Generated by Django 3.2.23 on 2026-09-22 16:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


def update_plan_prices(apps, schema_editor):
    """历史套餐调价：月会员 29.9 -> 9.9，年会员 299 -> 99。

    仅更新仍是旧默认价的标准套餐，管理员自定义过价格的套餐保持不变。
    """
    Plan = apps.get_model('membership', 'Plan')
    Plan.objects.filter(name='月会员', price='29.90').update(price='9.90')
    Plan.objects.filter(name='年会员', price='299.00').update(price='99.00')


def revert_plan_prices(apps, schema_editor):
    Plan = apps.get_model('membership', 'Plan')
    Plan.objects.filter(name='月会员', price='9.90').update(price='29.90')
    Plan.objects.filter(name='年会员', price='99.00').update(price='299.00')


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='10 表示无折扣；9 表示 9 折（按原价的 90% 收取）；8.5 表示 85 折。取值范围 0.01～10。', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='充值折扣（折）')),
            ],
            options={
                'verbose_name': '会员充值折扣',
                'verbose_name_plural': '会员充值折扣',
            },
        ),
        migrations.RunPython(update_plan_prices, revert_plan_prices),
    ]
