# Generated by Django 3.2.23 on 2026-09-22 16:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_rechargeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='下单瞬间的充值折扣快照，10 表示无折扣', max_digits=4, verbose_name='下单折扣（折）'),
        ),
    ]
