# Generated by Django 3.2.23 on 2026-09-25 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0003_order_discount_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='卡密')),
                ('kind', models.CharField(choices=[('member', '高级功能卡密'), ('starcoin', '星币卡密')], default='member', max_length=10, verbose_name='卡密类型')),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='仅高级功能卡密使用', verbose_name='高级功能天数')),
                ('coins', models.PositiveIntegerField(default=0, help_text='仅星币卡密使用', verbose_name='到账星币')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('disabled', '已作废')], default='unused', max_length=10, verbose_name='状态')),
                ('batch_no', models.CharField(blank=True, default='', max_length=32, verbose_name='批次号')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_card_keys', to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_card_keys', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
            ],
            options={
                'verbose_name': '卡密',
                'verbose_name_plural': '卡密',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cardkey',
            index=models.Index(fields=['batch_no'], name='membership__batch_n_cceecf_idx'),
        ),
    ]
