# Generated by Django 3.2.23 on 2025-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '选择题'), (2, '判断题')], verbose_name='题目类型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, help_text='选择题选项，格式：{"A":"选项内容","B":"选项内容"}', null=True, verbose_name='选项')),
                ('correct_answer', models.CharField(max_length=10, verbose_name='正确答案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['-created_at'],
            },
        ),
    ]
