# Generated by Django 3.2.23 on 2025-11-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='解析'),
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1, verbose_name='分值'),
        ),
    ]
