# Generated by Django 3.2.23 on 2025-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20251114_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='试卷标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='试卷描述')),
                ('total_score', models.IntegerField(default=0, verbose_name='总分')),
                ('created_by', models.CharField(default='admin', max_length=50, verbose_name='出题人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('questions', models.ManyToManyField(to='quiz.Question', verbose_name='包含题目')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['-created_at'],
            },
        ),
    ]
