# Generated by Django 3.2.23 on 2025-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answerrecord_profile_testrecord_wrongquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='选择题选项，格式：{"A":"选项内容","B":"选项内容"}', verbose_name='选项'),
        ),
    ]
