# Generated by Django 3.2.23 on 2025-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrecord',
            name='user_answer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='用户答案'),
        ),
    ]
