# Generated by Django 3.2.23 on 2025-11-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_answerrecord_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestion',
            name='user_answer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='用户错误答案'),
        ),
    ]
