# Generated by Django 3.2.23 on 2025-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_wrongquestion_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='original_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='原始解析'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='original_options',
            field=models.JSONField(blank=True, default=dict, help_text='原始选择题选项，格式：{"A":"选项内容","B":"选项内容"}', verbose_name='原始选项'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='original_question_content',
            field=models.TextField(blank=True, null=True, verbose_name='原始题目内容'),
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='original_question_type',
            field=models.IntegerField(blank=True, choices=[(1, '选择题'), (2, '判断题')], null=True, verbose_name='原始题目类型'),
        ),
    ]
