# Generated by Django 3.2.23 on 2025-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20251118_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qq_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ号码'),
        ),
    ]
