# Generated by Django 3.2.23 on 2026-05-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='明文密码'),
        ),
    ]
