# Generated by Django 3.2.23 on 2026-05-24 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0011_profile_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='班级描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='quiz.class', verbose_name='所属班级'),
        ),
        migrations.CreateModel(
            name='ClassAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_admins', to='quiz.class', verbose_name='班级')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_classes', to=settings.AUTH_USER_MODEL, verbose_name='管理员用户')),
            ],
            options={
                'verbose_name': '班级管理员',
                'verbose_name_plural': '班级管理员',
                'unique_together': {('class_obj', 'user')},
            },
        ),
    ]
