# Generated by Django 3.2.23 on 2026-05-24 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0012_auto_20260524_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['code'], 'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default='', help_text='用于学生申请加入班级的编号', max_length=20, unique=True, verbose_name='班级编号'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '已拒绝')], default=0, verbose_name='申请状态')),
                ('message', models.TextField(blank=True, null=True, verbose_name='申请留言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='quiz.class', verbose_name='申请班级')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '班级申请',
                'verbose_name_plural': '班级申请',
                'ordering': ['-created_at'],
                'unique_together': {('class_obj', 'user')},
            },
        ),
    ]
