# Generated by Django 3.2.23 on 2026-05-24 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0013_auto_20260524_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='作业标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='作业描述')),
                ('type', models.IntegerField(choices=[(1, '作业'), (2, '考试')], default=1, verbose_name='作业类型')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('status', models.IntegerField(choices=[(0, '未发布'), (1, '已发布')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quiz.class', verbose_name='班级')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('test_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='quiz.testpaper', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '班级作业',
                'verbose_name_plural': '班级作业',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassAssignmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='是否提交')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='得分')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='quiz.classassignment', verbose_name='作业')),
                ('test_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_record', to='quiz.testrecord', verbose_name='答题记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_records', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '班级作业记录',
                'verbose_name_plural': '班级作业记录',
                'unique_together': {('assignment', 'user')},
            },
        ),
    ]
