# Generated by Django 3.2.23 on 2026-05-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_add_class_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='is_wrong_paper',
            field=models.BooleanField(default=False, verbose_name='是否错题组卷'),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='出题人'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='test_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.testpaper', verbose_name='试卷'),
        ),
    ]
