# Generated by Django 3.2.23 on 2026-05-24 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20260525_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerrecord',
            options={'ordering': ['-answered_at'], 'verbose_name': '每题答题记录', 'verbose_name_plural': '每题答题记录'},
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 24, 16, 55, 16, 303842, tzinfo=utc), verbose_name='答题时间'),
            preserve_default=False,
        ),
    ]
