# Generated by Django 3.2.23 on 2026-05-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20260525_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plain_password',
        ),
    ]
