# Generated by Django 3.2.23 on 2026-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_remove_profile_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='source',
            field=models.CharField(choices=[('admin', '后台创建'), ('frontend', '前台创建')], default='frontend', max_length=20, verbose_name='试卷来源'),
        ),
        migrations.AlterField(
            model_name='answerrecord',
            name='original_question_type',
            field=models.IntegerField(blank=True, choices=[(1, '单选题'), (2, '多选题'), (3, '判断题')], null=True, verbose_name='原始题目类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '单选题'), (2, '多选题'), (3, '判断题')], verbose_name='题目类型'),
        ),
    ]
