# Generated by Django 3.2.23 on 2026-05-29 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20260525_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='章节编号')),
                ('title', models.CharField(max_length=100, verbose_name='章节标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='章节描述')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['subject', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='学科名称')),
                ('code', models.CharField(help_text='如 MATH, CHINESE', max_length=10, unique=True, verbose_name='学科代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='学科描述')),
                ('color', models.CharField(default='#667eea', help_text='十六进制颜色值', max_length=7, verbose_name='学科颜色')),
                ('icon', models.CharField(default='📚', help_text='Emoji图标', max_length=50, verbose_name='学科图标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='小节编号')),
                ('title', models.CharField(max_length=100, verbose_name='小节标题')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quiz.chapter', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '小节',
                'verbose_name_plural': '小节',
                'ordering': ['chapter', 'number'],
                'unique_together': {('chapter', 'number')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='知识点名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='知识点描述')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=2, verbose_name='难度等级')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_points', to='quiz.section', verbose_name='所属小节')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_points_all', to='quiz.subject', verbose_name='所属学科')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'ordering': ['subject', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='quiz.subject', verbose_name='所属学科'),
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.chapter', verbose_name='所属章节'),
        ),
        migrations.AddField(
            model_name='question',
            name='knowledge_points',
            field=models.ManyToManyField(blank=True, related_name='questions', to='quiz.KnowledgePoint', verbose_name='关联知识点'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.section', verbose_name='所属小节'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.subject', verbose_name='所属学科'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'number')},
        ),
    ]
