# Generated by Django 3.2.23 on 2026-05-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20260530_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, help_text='否表示私有题目，只有创建者和后台能看到', verbose_name='是否公开'),
        ),
    ]
