# Generated by Django 3.2.23 on 2026-05-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20260530_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='当前会话ID'),
        ),
    ]
