# Generated by Django 3.2.23 on 2026-05-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_add_profile_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='is_public',
            field=models.BooleanField(default=True, help_text='否表示私有试卷，只有创建者和后台能看到', verbose_name='是否公开'),
        ),
    ]
