# Generated by Django 3.2.23 on 2026-05-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_add_testpaper_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classassignmentrecord',
            options={'ordering': ['-submitted_at', '-start_time'], 'verbose_name': '班级作业记录', 'verbose_name_plural': '班级作业记录'},
        ),
        migrations.AddField(
            model_name='classassignment',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='仅考试模式有效，单位分钟', null=True, verbose_name='考试时长(分钟)'),
        ),
        migrations.AddField(
            model_name='classassignmentrecord',
            name='attempt',
            field=models.IntegerField(default=1, verbose_name='第几次提交'),
        ),
        migrations.AddField(
            model_name='classassignmentrecord',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始答题时间'),
        ),
        migrations.AlterUniqueTogether(
            name='classassignmentrecord',
            unique_together=set(),
        ),
    ]
