# Generated by Django 3.2.23 on 2026-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20260531_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='join_rule',
            field=models.CharField(choices=[('auto', '自动进班'), ('approval', '授权进班')], default='approval', max_length=20, verbose_name='进班规则'),
        ),
    ]
