# Generated by Django 3.2.23 on 2026-06-02 09:05
# Fake migration - field already exists in database

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20260601_0156'),
    ]

    operations = [
    ]
