# Generated by Django 3.2.23 on 2026-08-25 09:56

from django.db import migrations, models


def set_user_roles(apps, schema_editor):
    """根据现有数据回填用户角色：
    - is_staff=True → admin（管理员）
    - 是班级管理员(ClassAdmin)但非 is_staff → teacher（教师）
    - 其余保持 student（字段 default 已是 student）
    """
    Profile = apps.get_model('quiz', 'Profile')
    # 1. 管理员：is_staff 用户
    Profile.objects.filter(user__is_staff=True).update(role='admin')
    # 2. 教师：ClassAdmin 关系且非 is_staff
    try:
        ClassAdmin = apps.get_model('quiz', 'ClassAdmin')
        teacher_ids = list(
            ClassAdmin.objects.exclude(user__is_staff=True)
            .values_list('user_id', flat=True)
        )
        if teacher_ids:
            Profile.objects.filter(user_id__in=teacher_ids).update(role='teacher')
    except Exception:
        # ClassAdmin 模型不存在或字段异常时跳过，不影响主迁移
        pass


def reverse_roles(apps, schema_editor):
    """回滚：全部重置为 student"""
    Profile = apps.get_model('quiz', 'Profile')
    Profile.objects.all().update(role='student')


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_add_profile_stats'),
    ]

    operations = [
        # is_allow_exam 列数据库已存在（历史迁移 0028_add_is_random_to_class_assignment
        # 文件已丢失但列已加），用 SeparateDatabaseAndState 只更新 state 不动 DB
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='classassignment',
                    name='is_allow_exam',
                    field=models.BooleanField(default=True, verbose_name='是否允许考试'),
                ),
            ],
            database_operations=[],
        ),
        # name 列数据库已存在（历史迁移 0029_fix_missing_fields 文件已丢失但列已加），
        # 用 SeparateDatabaseAndState 只更新 state 不动 DB
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='profile',
                    name='name',
                    field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '管理员')], default='student', max_length=10, verbose_name='用户角色'),
        ),
        # 数据迁移：回填现有用户角色
        migrations.RunPython(set_user_roles, reverse_code=reverse_roles),
    ]
