# Generated by Django 3.2.23 on 2026-08-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_auto_20260825_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrongquestion',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次复习时间'),
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次复习时间'),
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='复习次数'),
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='review_status',
            field=models.CharField(choices=[('new', '未复习'), ('reviewing', '复习中'), ('mastered', '已掌握'), ('difficult', '顽固错题')], default='new', max_length=10, verbose_name='复习状态'),
        ),
    ]
