# Generated by Django 3.2.23 on 2026-08-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='duration',
            field=models.IntegerField(blank=True, help_text='为空表示不限时；设置后答题页显示倒计时，到时自动交卷', null=True, verbose_name='考试时长(分钟)'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='为空表示无截止', null=True, verbose_name='开放结束时间'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='max_attempts',
            field=models.IntegerField(blank=True, help_text='为空表示不限次数', null=True, verbose_name='最大答题次数'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='为空表示立即开放', null=True, verbose_name='开放开始时间'),
        ),
    ]
