# Generated by manual on 2026-08-26
# 历史迁移 0028_add_is_random_to_class_assignment 文件已丢失，但数据库列已存在；
# 此迁移只同步 Django state（模型已补 is_random/random_config 字段），不动数据库。
# 否则 ORM 创建 ClassAssignment 时 INSERT 不含这两列，MySQL 严格模式报 1364。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_p2_3_exam_control'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='classassignment',
                    name='is_random',
                    field=models.BooleanField(default=False, verbose_name='是否随机出题'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='classassignment',
                    name='random_config',
                    field=models.JSONField(blank=True, default=dict, verbose_name='随机出题配置'),
                ),
            ],
            database_operations=[],
        ),
    ]
