# Generated by Django 3.2.23 on 2026-08-27 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0032_classassignment_random_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wrong_paper', models.BooleanField(default=False, verbose_name='是否错题组卷')),
                ('answers', models.JSONField(default=dict, verbose_name='答题内容')),
                ('current_index', models.IntegerField(default=0, verbose_name='逐题答题位置')),
                ('mode', models.CharField(default='full', max_length=10, verbose_name='答题模式')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后保存时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.classassignment', verbose_name='班级作业')),
                ('test_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.testpaper', verbose_name='试卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drafts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '答题草稿',
                'verbose_name_plural': '答题草稿',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='testdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('test_paper__isnull', False)), fields=('user', 'test_paper', 'is_wrong_paper'), name='uniq_draft_test_paper'),
        ),
        migrations.AddConstraint(
            model_name='testdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment__isnull', False)), fields=('user', 'assignment'), name='uniq_draft_assignment'),
        ),
    ]
