# Generated by Django 3.2.23 on 2026-08-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_auto_20260827_1516'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testdraft',
            name='uniq_draft_test_paper',
        ),
        migrations.RemoveConstraint(
            model_name='testdraft',
            name='uniq_draft_assignment',
        ),
        migrations.AddConstraint(
            model_name='testdraft',
            constraint=models.UniqueConstraint(fields=('user', 'test_paper', 'is_wrong_paper'), name='uniq_draft_test_paper'),
        ),
        migrations.AddConstraint(
            model_name='testdraft',
            constraint=models.UniqueConstraint(fields=('user', 'assignment'), name='uniq_draft_assignment'),
        ),
    ]
