# Generated by Django 3.2.23 on 2026-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20260827_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='明文密码'),
        ),
    ]
