# Generated by Django 3.2.23 on 2026-09-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_wrongquestion_correct_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='答题用时(秒)'),
        ),
    ]
