# Generated by Django 3.2.23 on 2026-09-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0039_leaderboard_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='accuracy_rate',
        ),
    ]
