# Generated by Django 3.2.23 on 2026-09-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_remove_profile_accuracy_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_approval_status', models.IntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核拒绝')], default=1, help_text='新用户注册后自动写入的会员审核状态默认值', verbose_name='注册用户默认审核状态')),
                ('default_member_days', models.PositiveIntegerField(default=0, help_text='新用户注册后自动按该天数设置会员到期时间；0 表示不设到期时间（仅记录开始时间）', verbose_name='注册默认会员时长（天）')),
            ],
            options={
                'verbose_name': '会员默认设置',
                'verbose_name_plural': '会员默认设置',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='member_expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='会员开始时间'),
        ),
    ]
