# Generated by Django 3.2.23 on 2026-09-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_siteconfig_profile_member_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后活动时间'),
        ),
    ]
