# Generated by Django 3.2.23 on 2026-09-20 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """试卷成绩等级线：把原先写死在代码里的 60%/80%（及分段用的 70%）改为按试卷配置。

    默认值 60/70/80 与历史口径一致，历史数据无需回填，行为保持不变。
    """

    dependencies = [
        ('quiz', '0044_testpaper_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='excellent_rate',
            field=models.PositiveIntegerField(default=80, help_text='得分率达到该百分比视为优秀，默认 80', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='优秀得分率(%)'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='good_rate',
            field=models.PositiveIntegerField(default=70, help_text='得分率达到该百分比视为良好（分段统计用），默认 70', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='良好得分率(%)'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='pass_rate',
            field=models.PositiveIntegerField(default=60, help_text='得分率达到该百分比视为及格，默认 60', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='及格得分率(%)'),
        ),
    ]
