# Generated by Django 3.2.23 on 2026-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0045_testpaper_grade_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_frame',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='头像框'),
        ),
        migrations.AddField(
            model_name='profile',
            name='conquered_bonus',
            field=models.PositiveIntegerField(default=0, verbose_name='斩题加成'),
        ),
    ]
