# Generated by Django 3.2.23 on 2026-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0046_auto_20260924_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='公告标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='公告内容')),
                ('level', models.CharField(choices=[('info', '普通（蓝色）'), ('success', '成功（绿色）'), ('warning', '提醒（橙色）'), ('danger', '重要（红色）')], default='info', max_length=10, verbose_name='公告级别')),
                ('display_mode', models.CharField(choices=[('scroll', '滚动条（横向滚动）'), ('static', '公告板（列表展示）')], default='scroll', max_length=10, verbose_name='展示形态')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, help_text='数值越小越靠前', verbose_name='排序')),
                ('start_at', models.DateTimeField(blank=True, help_text='留空表示立即生效', null=True, verbose_name='生效时间')),
                ('end_at', models.DateTimeField(blank=True, help_text='留空表示长期有效', null=True, verbose_name='失效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
