# Generated by Django 3.2.23 on 2026-09-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0047_announcement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='idx_noti_recip_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='idx_noti_recip_time'),
        ),
        migrations.AddIndex(
            model_name='testrecord',
            index=models.Index(fields=['user', 'test_paper'], name='idx_record_user_paper'),
        ),
        migrations.AddIndex(
            model_name='testrecord',
            index=models.Index(fields=['user', 'completed_at'], name='idx_record_user_time'),
        ),
        migrations.AddIndex(
            model_name='wrongquestion',
            index=models.Index(fields=['user', 'review_status'], name='idx_wrong_user_status'),
        ),
    ]
