# Generated by Django 3.2.23 on 2026-09-24 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='道具名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='道具说明')),
                ('icon', models.CharField(default='🎁', max_length=10, verbose_name='图标')),
                ('category', models.CharField(blank=True, default='', max_length=30, verbose_name='分类')),
                ('price_coins', models.PositiveIntegerField(verbose_name='所需星币')),
                ('stock', models.IntegerField(default=-1, help_text='-1 表示不限库存', verbose_name='库存')),
                ('per_user_limit', models.PositiveIntegerField(default=0, help_text='0 表示不限购', verbose_name='每人限购')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '星币道具',
                'verbose_name_plural': '星币道具',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StarPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='套餐名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格（元）')),
                ('coins', models.PositiveIntegerField(verbose_name='基础星币')),
                ('bonus_coins', models.PositiveIntegerField(default=0, verbose_name='赠送星币')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '星币套餐',
                'verbose_name_plural': '星币套餐',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('daily_login', '每日登录'), ('submit_paper', '完成试卷'), ('pass_paper', '试卷达标'), ('submit_assignment', '完成班级作业'), ('conquer_question', '答对题目（斩题）')], max_length=32, unique=True, verbose_name='任务标识')),
                ('name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='任务说明')),
                ('icon', models.CharField(default='⭐', max_length=10, verbose_name='图标')),
                ('reward_coins', models.PositiveIntegerField(default=1, verbose_name='奖励星币')),
                ('period', models.CharField(choices=[('once', '仅一次'), ('daily', '每日一次'), ('unlimited', '每次触发（按每日次数限制）')], default='daily', max_length=10, verbose_name='发放周期')),
                ('daily_limit', models.PositiveIntegerField(default=0, help_text='仅「每次触发」类型生效；0 表示不限制', verbose_name='每日最多发放次数')),
                ('threshold', models.PositiveIntegerField(default=0, help_text='仅「试卷达标」任务生效；按得分百分比判定，0 表示不限制', verbose_name='达标分数线（%）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '星币任务',
                'verbose_name_plural': '星币任务',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StarTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='变动数量')),
                ('balance_after', models.BigIntegerField(verbose_name='变动后余额')),
                ('kind', models.CharField(choices=[('recharge', '充值获得'), ('active', '活跃奖励'), ('redeem', '道具兑换'), ('refund', '兑换退回'), ('admin_adjust', '管理员调整')], max_length=20, verbose_name='类型')),
                ('ref_type', models.CharField(blank=True, default='', max_length=20, verbose_name='来源类型')),
                ('ref_id', models.CharField(blank=True, default='', max_length=64, verbose_name='来源标识')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '星币流水',
                'verbose_name_plural': '星币流水',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StarTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(max_length=32, verbose_name='周期标识')),
                ('reward_coins', models.PositiveIntegerField(default=0, verbose_name='发放星币')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发放时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='starcoin.startask', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_task_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '星币任务记录',
                'verbose_name_plural': '星币任务记录',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StarRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='兑换数量')),
                ('coins_cost', models.PositiveIntegerField(verbose_name='消耗星币')),
                ('status', models.CharField(choices=[('pending', '待发放'), ('fulfilled', '已发放'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('contact', models.CharField(blank=True, default='', help_text='收货地址/联系方式，便于后台发放', max_length=200, verbose_name='联系方式')),
                ('user_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='用户留言')),
                ('admin_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='处理备注')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='star_fulfilled_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='starcoin.staritem', verbose_name='道具')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '星币兑换记录',
                'verbose_name_plural': '星币兑换记录',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StarRechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='商户订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='订单金额（元）')),
                ('coins', models.PositiveIntegerField(verbose_name='到账星币')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('closed', '已关闭')], default='pending', max_length=10, verbose_name='状态')),
                ('trade_no', models.CharField(blank=True, default='', max_length=64, verbose_name='支付宝交易号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='starcoin.starpackage', verbose_name='套餐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '星币充值订单',
                'verbose_name_plural': '星币充值订单',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, verbose_name='当前星币余额')),
                ('active_earned', models.BigIntegerField(default=0, verbose_name='活跃奖励累计获得')),
                ('recharge_earned', models.BigIntegerField(default=0, verbose_name='充值累计获得')),
                ('total_spent', models.BigIntegerField(default=0, verbose_name='累计消耗')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='star_account', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '星币账户',
                'verbose_name_plural': '星币账户',
                'ordering': ['-balance', 'user_id'],
            },
        ),
        migrations.AddIndex(
            model_name='startransaction',
            index=models.Index(fields=['user', '-created_at'], name='starcoin_st_user_id_fc676f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='startaskrecord',
            unique_together={('user', 'task', 'period_key')},
        ),
        migrations.AddIndex(
            model_name='staraccount',
            index=models.Index(fields=['-balance'], name='starcoin_st_balance_3ccea5_idx'),
        ),
        migrations.AddIndex(
            model_name='staraccount',
            index=models.Index(fields=['-active_earned'], name='starcoin_st_active__dc813b_idx'),
        ),
    ]
