# Generated by Django 3.2.23 on 2026-09-24 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('starcoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startask',
            name='code',
            field=models.CharField(choices=[('daily_login', '每日登录'), ('submit_paper', '完成试卷'), ('pass_paper', '试卷达标'), ('submit_assignment', '完成班级作业'), ('conquer_question', '答对题目（斩题）'), ('login_streak_7', '连续登录 7 天'), ('login_streak_30', '连续登录 30 天'), ('share_leaderboard', '分享榜单')], max_length=32, unique=True, verbose_name='任务标识'),
        ),
        migrations.AlterField(
            model_name='startask',
            name='period',
            field=models.CharField(choices=[('once', '仅一次'), ('daily', '每日一次'), ('unlimited', '每次触发（按每日次数限制）'), ('milestone', '里程碑（按连续天数循环发放）')], default='daily', max_length=10, verbose_name='发放周期'),
        ),
        migrations.CreateModel(
            name='StarLoginStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_days', models.PositiveIntegerField(default=0, verbose_name='当前连续天数')),
                ('longest_days', models.PositiveIntegerField(default=0, verbose_name='历史最长连续天数')),
                ('streak_start_date', models.DateField(blank=True, null=True, verbose_name='本轮起始日期')),
                ('last_login_date', models.DateField(blank=True, null=True, verbose_name='最后登录日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='star_login_streak', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '连续登录',
                'verbose_name_plural': '连续登录',
                'ordering': ['-current_days', 'user_id'],
            },
        ),
    ]
