# Generated by Django 3.2.23 on 2026-09-24 12:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcoin', '0002_auto_20260924_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='staritem',
            name='member_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='仅会员生效中的用户享受；10 表示无折扣，9 表示会员 9 折。取值范围 0.01～10。', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='会员折扣（折）'),
        ),
        migrations.AddField(
            model_name='starredemption',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='兑换瞬间的会员折扣快照，10 表示无折扣', max_digits=4, verbose_name='兑换折扣（折）'),
        ),
        migrations.AddField(
            model_name='starredemption',
            name='original_coins',
            field=models.PositiveIntegerField(default=0, verbose_name='原价星币'),
        ),
    ]
