# Generated by Django 3.2.23 on 2026-09-24 14:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('starcoin', '0003_auto_20260924_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='staritem',
            name='effect_payload',
            field=models.JSONField(blank=True, default=dict, help_text='会员卡示例 {"days": 30}；斩题卡示例 {"count": 1}；头像框示例 {"frame": "gold"}', verbose_name='效果参数'),
        ),
        migrations.AddField(
            model_name='staritem',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('', '无（人工核销发放）'), ('rename_card', '改名卡'), ('wrong_paper_card', '错题组卷卡'), ('accuracy_reset', '正确率重置卡'), ('hint_card', '答案提示卡'), ('avatar_frame', '头像框'), ('conquer_card', '斩题卡'), ('member_card', '会员卡')], default='', help_text='留空 = 人工核销发放；选择后由系统自动发放（即时生效或入背包）', max_length=20, verbose_name='道具效果'),
        ),
        migrations.AddField(
            model_name='starredemption',
            name='used_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='已使用数量'),
        ),
        migrations.AlterField(
            model_name='staritem',
            name='member_discount_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='仅会员生效中的用户享受；10 表示无折扣，9 表示会员 9 折。取值范围 0.01～10。会员卡类道具会被强制锁定为 10（无折扣）。', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='会员折扣（折）'),
        ),
        migrations.CreateModel(
            name='StarItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(blank=True, default='', max_length=20, verbose_name='效果类型')),
                ('detail', models.CharField(blank=True, default='', max_length=200, verbose_name='使用明细')),
                ('context', models.CharField(blank=True, default='', max_length=50, verbose_name='使用场景')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='使用时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='starcoin.staritem', verbose_name='道具')),
                ('redemption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='starcoin.starredemption', verbose_name='来源兑换记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_item_usages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '道具使用流水',
                'verbose_name_plural': '道具使用流水',
                'ordering': ['-id'],
            },
        ),
    ]
