# Generated by Django 3.2.23 on 2026-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcoin', '0007_login_gift_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarWrongPaperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_daily_limit', models.PositiveIntegerField(default=1, help_text='免费用户每天可不消耗组卷卡组卷的次数（每次最多 10 题）；0 表示关闭免费额度（每次组卷都要用卡）。会员不受此限制。', verbose_name='免费用户每日免费组卷次数')),
            ],
            options={
                'verbose_name': '错题组卷额度',
                'verbose_name_plural': '错题组卷额度',
            },
        ),
    ]
