# Generated by Django 3.2.23 on 2026-09-26 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starcoin', '0010_alter_starwrongpaperconfig_free_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='starwrongpaperconfig',
            name='free_max_questions',
            field=models.PositiveIntegerField(default=20, help_text='免费用户不用组卷卡时，单次组卷最多可选题数；超出必须用组卷卡（用卡当次不限题量）。', validators=[django.core.validators.MinValueValidator(1)], verbose_name='免费用户单次组卷题数上限'),
        ),
        migrations.AddField(
            model_name='starwrongpaperconfig',
            name='member_max_questions',
            field=models.PositiveIntegerField(default=20, help_text='高级功能（会员）用户不用组卷卡时，单次组卷最多可选题数；超出必须用组卷卡（用卡当次不限题量）。', validators=[django.core.validators.MinValueValidator(1)], verbose_name='高级用户单次组卷题数上限'),
        ),
        migrations.AlterField(
            model_name='starwrongpaperconfig',
            name='free_daily_limit',
            field=models.PositiveIntegerField(default=1, help_text='免费用户每天可不消耗组卷卡组卷的次数；0 表示关闭免费额度（每次组卷都要用卡）。会员不受此限制。', verbose_name='免费用户每日免费组卷次数'),
        ),
    ]
